name: "Generate Refit API Client using Refitter"
description: "Generates a Refit Client SDK using Refitter from an OpenAPI Specifications file"
branding:
  icon: code
  color: green

inputs:
  openapi-url:
    description: If set, the OpenAPI document will be loaded from this URL instead of openapi-file.
    required: false
  openapi-file:
    description: The path to the OpenAPI document to generate a client library for
    required: false
    default: openapi.json
  namespace:
    description: The default namespace used for the generated types
    required: false   
  use-api-response:
    description: Return Task<IApiResponse<T>> instead of Task<T>
    required: false
    default: false
    type: boolean
  cancellation-tokens:
    description: Use cancellation tokens
    required: false
    default: false
    type: boolean
  command-args:
    description: Optional, additional arguments to pass through to Refitter
    required: false
    type: string
  publish-artifacts:
    description: Setting this will publish the generated code as C# files
    required: false
    type: boolean
    default: true
    
  version:
    description: The version number used for the NuGet package
    required: false
    type: string
    default: 1.0.${{ github.run_number }}
  target-framework:
    description: The target framework used in the Client SDK
    required: false
    type: string
    default: net6.0
  package-id:
    required: false
    type: string
  title:
    required: false
    type: string
  root-namespace:
    required: false
    type: string
  assembly:
    required: false
    type: string
  authors:
    required: false
    type: string
  product:
    required: false
    type: string
  company:
    required: false
    type: string
  description:
    required: false
    type: string
  project-url:
    required: false
    type: string
  license:
    required: false
    type: string
    default: GPL-3.0-only
  repository-type:
    required: false
    type: string
    default: git
    

runs:
  using: composite
  steps:

    - name: Generate Client Interface
      uses: refitter/generate-code@v1
      with:
        openapi-url: https://petstore3.swagger.io/api/v3/openapi.json
        namespace: ChristianHelle.Examples.Petstore.v3
        command-args: ${{ inputs.command-args }}
        use-api-response: ${{ inputs.use-api-response }}
        cancellation-tokens: ${{ inputs.cancellation-tokens }}
        publish-artifacts: false

    - name: Generated C# project
      run: |
        @'
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <TargetFramework>${{ inputs.target-framework }}</TargetFramework>
            <LangVersion>latest</LangVersion>
            <Nullable>enable</Nullable>
            <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
            <Authors>${{ inputs.authors }}</Authors>
            <Product>${{ inputs.product }}</Product>
            <PackageId>${{ inputs.package-id }}</PackageId>
            <AssemblyName>${{ inputs.assembly }}</AssemblyName>
            <Company>${{ inputs.company }}</Company>
            <Description>${{ inputs.description }}</Description>
            <PackageLicenseExpression>${{ inputs.license }}</PackageLicenseExpression>
            <PackageProjectUrl>${{ inputs.project-url }}</PackageProjectUrl>
            <RepositoryUrl>${{ inputs.project-url }}</RepositoryUrl>
            <RepositoryType>${{ inputs.repository-type }}</RepositoryType>
            <PublishRepositoryUrl>true</PublishRepositoryUrl>
            <DebugType>embedded</DebugType>
            <EmbedUntrackedSources>true</EmbedUntrackedSources>
            <IsPackable>true</IsPackable>
            <TieredCompilation>true</TieredCompilation>
          </PropertyGroup>
          <ItemGroup>
            <PackageReference Include="Refit" Version="6.3.2" />
            <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
            <PackageReference Include="System.ComponentModel.Annotations" Version="4.5.0" />
            <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
          </ItemGroup>
        </Project>
        '@ | Out-File Build.csproj
        Get-Content Build.csproj | Write-Host
      shell: pwsh

    - name: Build
      run: dotnet build -c Release /p:UseSourceLink=true -p:PackageVersion="${{ inputs.version }}"
      shell: pwsh

    - name: Pack
      run: dotnet pack --no-build -c Release /p:UseSourceLink=true -p:PackageVersion="${{ inputs.version }}" --output .
      shell: pwsh

    - name: Publish Client SDK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: NuGet Pacakge
        path: |
          **/*.nupkg
