name: Smoke Tests (Main branch)

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'      
      - '!action.yml'
      - '!.github/workflows/smoke-tests.yml'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  smoke-test:
    name: From URL with Client SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: Generate Refit Client SDK
        with:
          openapi-url: https://petstore3.swagger.io/api/v3/openapi.json
          namespace: ChristianHelle.Examples.Petstore.v3
          command-args: --no-logging
          version: 1.0.${{ github.run_number }}
          package-id: ChristianHelle.Examples.Petstore.v3
          title: ChristianHelle.Examples.Petstore.v3
          root-namespace: ChristianHelle.Examples.Petstore.v3
          assembly: ChristianHelle.Examples.Petstore.v3
          product: ChristianHelle.Examples.Petstore
          authors: Christian Resma Helle
          company: Christian Resma Helle
          description: Example generated code using Refitter and the Swagger Petstore v3 example OpenAPI specifications
          project-url: https://github.com/christianhelle/refitter-action